/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms.index'
import { Route as AlgorithmsNameRouteImport } from './routes/algorithms.$name'

const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsNameRoute = AlgorithmsNameRouteImport.update({
  id: '/algorithms/$name',
  path: '/algorithms/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/algorithms/$name': typeof AlgorithmsNameRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/algorithms/$name': typeof AlgorithmsNameRoute
  '/algorithms': typeof AlgorithmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/algorithms/$name': typeof AlgorithmsNameRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/compare'
    | '/algorithms/$name'
    | '/algorithms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analysis'
    | '/compare'
    | '/algorithms/$name'
    | '/algorithms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/compare'
    | '/algorithms/$name'
    | '/algorithms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRoute
  CompareRoute: typeof CompareRoute
  AlgorithmsNameRoute: typeof AlgorithmsNameRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms/'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$name': {
      id: '/algorithms/$name'
      path: '/algorithms/$name'
      fullPath: '/algorithms/$name'
      preLoaderRoute: typeof AlgorithmsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRoute,
  CompareRoute: CompareRoute,
  AlgorithmsNameRoute: AlgorithmsNameRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
